### PR TITLE
gadgets: Update vmlinux.h

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
Update vmlinux and use core_fixes from BCC to fix some compiling errors.

### CODE REVIEW

File: pkg/gadgets/trace/tcpdrop/tracer/bpf/tcpdrop.bpf.c [hunk 1]
```diff
@@ -118,29 +106,20 @@ static __always_inline int __trace_tcp_drop(void *ctx, struct sock *sk, struct s
...
-// enum skb_drop_reason is defined in the following file:
-// https://raw.githubusercontent.com/torvalds/linux/v6.2/include/net/dropreason.h
-// Here we only need SKB_DROP_REASON_NOT_SPECIFIED
-enum skb_drop_reason {
-	SKB_NOT_DROPPED_YET = 0,
-	SKB_CONSUMED,
-	SKB_DROP_REASON_NOT_SPECIFIED
-};
-
 SEC("tracepoint/skb/kfree_skb")
```
Comment (alban) [inline pkg/gadgets/trace/tcpdrop/tracer/bpf/tcpdrop.bpf.c:121]: I tested that it works fine on my kernel (`5.18.9-200.fc36.x86_64`):
```
$ sudo bpftool btf  dump id 1 format c| grep -A 50 'enum skb_drop_reason {'
enum skb_drop_reason {
        SKB_NOT_DROPPED_YET = 0,
        SKB_DROP_REASON_NOT_SPECIFIED = 1,
...
	SKB_DROP_REASON_QDISC_DROP = 34,
```
And indeed it matches [include/linux/skbuff.h#L316-L318](https://github.com/torvalds/linux/blob/v5.18/include/linux/skbuff.h#L316-L318):
```
enum skb_drop_reason {
        SKB_NOT_DROPPED_YET = 0,
        SKB_DROP_REASON_NOT_SPECIFIED,  /* drop reason is not specified */
...
	SKB_DROP_REASON_QDISC_DROP,	/* dropped by qdisc when packet
					 * outputting (failed to enqueue to
					 * current qdisc)
					 */
```

Then, tcpdrop shows `QDISC_DROP` from id 34 correctly.

**Comment by alban** [comment]
I don't understand how core_fixes works, but the changes on tcpdrop look good to me.

**Comment by mauriciovasquezbernal** [comment]
> Please add in the commit message what were the compilation errors.

I'm sorry I didn't record this. Doing so would require some manual work so I prefer to omit it this time.
